input_folder: results/phase1/AT_Dn+CBAM_26/1_DenseNet201_reports/

target_confusions:
  - [sinapis, olea]
  - [calicotome, olea]
  - [ceratonia, eucalyptus]
  - [origanum, ceratonia]

output_csv: results/discussion/phase1/AT_Dn+CBAM_26/1_DenseNet201_reports_consolidated/A500_confusion_summary.csv
