path_model: "results/phase1/AT_Dn+CBAM_26/1_DenseNet201/"
path_full_labels: "BD/CPD1_Cr_Rs_500/Test/k1"  
path_test: "BD/CPD1_TEST_A500/"   # Directory to save the distribution chart
save_dir: "results/phase3/"  # Directory to save the distribution graph
save: 1  # 1 to save resized images, 0 to not save
verbose: 1  # 1 for detailed output, 0 for silent mode
size: 224
